# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barren, Frozen Wasteland
email: mark@barrenfrozenwasteland.com
description: 'Mark Johnson&#039;s Blog of Tech, Ubuntu and Stuff'
baseurl: "/bfwl"
url: https://barrenfrozenwasteland.com
twitter_username: marxjohnson
github_username:  marxjohnson

# Build settings
markdown: kramdown
